version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: shorty-db
    environment:
      POSTGRES_USER: shorty
      POSTGRES_PASSWORD: shorty
      POSTGRES_DB: shorty
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shorty"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shorty-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://shorty:shorty@db:5432/shorty
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      BASE_URL: http://localhost:8080
      RUST_LOG: info
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
